### ISSUE TITLE
Language mutations

### ISSUE THREAD

**Issue by vojtechsimetka** [Giveth/Website-3.0#1]
Externalise language mutations so that the content and the visuals are separate. You can find good example on how to do this correctly at [this awesome boilerplate](https://github.com/react-boilerplate/react-boilerplate)

**Comment by GriffGreen** [comment]
This is incredibly important! In fact we already have a spanish version ready to go ;-) thx to @alexshelpin on the slack! 

https://docs.google.com/document/d/1Xc4djoVZLXzwNDmg5K1RqiETjS07dNbp8ntPlPV0B_I/edit?usp=sharing
